### ISSUE TITLE
@types should be devDependencies

### ISSUE THREAD

**Issue by scottbessler** [xavdid/json-requests#3]
https://github.com/xavdid/json-requests/blob/7d01541476fee76875dca887814afe30f4076a3d/package.json#L58

**Comment by xavdid** [comment]
Interesting! I was under the impression that you generally wanted to ship your dependent types so any parts of your public API that depended on node would work for consumers, as described here: https://stackoverflow.com/a/46011417/1825390

But given that my public API is primitives, maybe that's not required here. Also I can't find any of my other packages that include types in deps, so maybe I'm misremembering a thing you used to need to do.

Either way, thanks for looking! I'll get it moved.
